### ISSUE TITLE
Minimum version requirements for libuv

### ISSUE THREAD

**Issue by slimhazard** [Qihoo360/logkafka#2]
Debian jessie packages libuv version 0.10, and building logkafka with that results in this error:
```
[  7%] Building CXX object src/CMakeFiles/logkafka.dir/logkafka/tail_watcher.cc.o
In file included from /home/geoff/Software/logkafka/src/logkafka/tail_watcher.h:32:0,
                 from /home/geoff/Software/logkafka/src/logkafka/tail_watcher.cc:22:
/home/geoff/Software/logkafka/src/base/stat_watcher.h:65:23: error: ‘uv_stat_t’ does not name a type
                 const uv_stat_t* prev, 
                       ^
/home/geoff/Software/logkafka/src/base/stat_watcher.h:66:23: error: ‘uv_stat_t’ does not name a type
                 const uv_stat_t* curr);
                       ^
src/CMakeFiles/logkafka.dir/build.make:146: recipe for target 'src/CMakeFiles/logkafka.dir/logkafka/tail_watcher.cc.o' failed
```
From a look at the libuv github, the type ```uv_stat_t``` was evidently introduced in version 0.11 (previously ```uv_statbuf_t```).

After cloning the libuv git and building the current version from source (presently 1.7.6), the logkafka build succeeded.

So I can't say exactly which minimum version of libuv is required for logkafka -- at least 0.11, and I would guess probably 1.x. You might want to mention that in the install instructions.

**Comment by zheolong** [comment]
libuv version > v1.6.0, added to README
